### ISSUE TITLE
Is 64bit CPU suppored [Android]?

### ISSUE THREAD

**Issue by Darkoon** [brodybits/cordova-sqlcipher-adapter#51]
Hi!
Like in the title, I want to know if the 64bit architectures are supported now?  (x86_64 and arm64).
From your repo status description:

> SQLCipher 3.5.6 for Android built from brodybits / android-database-sqlcipher-build-fix, now with 64-bit CPU support

> NOTE: 64-bit CPUs such as x64_64, ARM-64, and MIPS are currently not supported by the SQLCipher for Android build (support for these CPUs is for future consideration).

Which statement is true for now?

**Comment by brodybits** [comment]
> Like in the title, I want to know if the 64bit architectures are supported now? (x86_64 and arm64).

Yes

> Which statement is true for now?

The first one. The second statement is now removed with strikethrough, should be completely removed in the near future.

**Comment by brody2consult** [comment]
> The second statement is now removed with strikethrough, should be completely removed in the near future.

Should be completely gone now. Note that MIPS was never supported by SQLCipher for Android and was dropped by Android NDK.
