### ISSUE TITLE
"You don’t have permission to save the file “CallDirectory” in the folder “Library”

### ISSUE THREAD

**Issue by sezmars** [brodybits/cordova-sqlcipher-adapter#55]
Hi, guys. I have a problem that I can not solve. I develop on ionic 2. At first I used native sqlite plugin ( https://github.com/litehelpers/Cordova-sqlite-storage, https://ionicframework.com/docs/native/sqlite/ ), but it did not work correctly with database encryption. So I decided to use your plugin and I managed to configure the encryption on Android. The problem occurs when I run the application on ios. That's what he wrote in the console: 
1. 
> You don’t have permission to save the file “CallDirectory” in the folder “Library”
UserInfo={NSFilePath=/var/mobile/Library/CallDirectory, NSUnderlyingError=0x7fa42fd14f40 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}} 

and code for create/open database

2. 
> createDataBase() {
    this.storageData.getUsername().then((name) => {
      if (!this.isOpen) {
        this.uniqueDeviceID.get()
          .then((uuid: any) => {
            this.db = window.sqlitePlugin.openDatabase({
              name: name + '.db', //Name is the username
              key: uuid, // Unique value of the phone
              iosDatabaseLocation: 'default'
            }, (db) => {
              db.transaction((tx) => {
                tx.executeSql("CREATE TABLE IF NOT EXISTS accounts (id INTEGER PRIMARY KEY AUTOINCREMENT, cfid INTEGER, cfopd TEXT, compareDate TEXT,  cfac TEXT, cfopvin INTEGER, cfopvout INTEGER,  cfcl TEXT, cfit TEXT,  acompid TEXT, aname TEXT,  aval TEXT, aisc INTEGER, cname TEXT, uname TEXT)", [], (tx, data) => {
                  this.isOpen = true;
                })
              }, function (error) {
                console.log('Transaction ERROR: ' + error.message)
              }, function () {
                console.log('Populated database OK');
              });
            })
          })
      }
    });
  }

I searched a lot, but I did not find a solution. Who has any ideas? Thanks

**Comment by brodybits** [comment]
My apologies for the delay, not sure if I can follow. Maybe a test app based on <https://github.com/brodybits/cordova-sqlite-test-app> that can demonstrate the issue?

**Comment by brodybits** [comment]
I really cannot do anything without a test app, and I generally do not support Ionic due to the number of problems over the past years.

**Comment by sezmars** [comment]
no no
I'm just asking whether you can remove this particular issue?

вт, 5 нояб. 2019 г. в 20:44, Chris Brody <notifications@github.com>:

**Comment by brodybits** [comment]
I really do not understand what you mean by "remove this particular issue".

**Comment by sezmars** [comment]
вт, 5 нояб. 2019 г. в 20:47, Chris Brody <notifications@github.com>:

**Comment by brodybits** [comment]
Closing and locking this issue due to lack of useful information. In case anyone encounters this or another similar issue please feel free to raise a new issue with a test app, based on <https://github.com/brodybits/cordova-sqlite-test-app>, with no use of Ionic.

**Comment by brodybits** [comment]
Issue raised is not deleted since it is for the benefit for anyone in the user community. For discussion please raise a new issue.

Ionic is known to have problems with this plugin and with Cordova in general.

No private discussion.
