### ISSUE TITLE
Check if encrypted database exists while locked

### ISSUE THREAD

**Issue by RyanTully** [brodybits/cordova-sqlcipher-adapter#56]
Hi Chris, 
This is a great plugin, Thanks!

I'm using sqlcipher and I want to determine (without the key) if a database has been created so that if the DB is closed or if the app restarts I can present the relevant UI to the user i.e. create password if no DB exists yet or login/forgot passcode if the DB does exist but it's closed.

I assume the only way to test this without the key is to determine if a DB file exists. I've read through some of the posts relating to DB file location e.g. https://github.com/litehelpers/Cordova-sqlite-storage/issues/223 but the file locations mentioned here don't seem work.

on iOS I've tried - 
`window.resolveLocalFileSystemURL("cdvfile://localhost/persistent/<database.name>"` and 
`window.resolveLocalFileSystemURL(cordova.file.applicationStorageDirectory + "/<database.name>"` but neither return a success callback.

You mention the location is or will be noted in the readme but I can't seem to find it.

Is there a set location for the DB file or can it be determined? 

If there's an alternative way of checking if a closed DB exists could you point me in the right direction?

I would need to determine this for both iOS and Android platforms

Any help would be appreciated.

Thanks

Ryan

**Comment by brodybits** [comment]
My apologies for the delay. Not sure if I can completely follow your question. Maybe a sample project that shows what you are trying to do and what does not work would help.

**Comment by RyanTully** [comment]
Hi Chris,

Apologies for my delayed response. I stepped away from this part of the project for some time and must have missed your reply over the Christmas Period. I've managed to figure out the location of the Database file now so problem solved. Thanks for getting back to me anyway.

Ryan
